#!/usr/bin/env python3
"""Release Otii Learn to an otii project on Northflank. Safe to rerun.

    python3 otii/northflank/deploy.py staging
    python3 otii/northflank/deploy.py production --confirm-production
    python3 otii/northflank/deploy.py staging --check      # guards and room only, no changes

Refuses unless: the tree is clean and pushed, the template passes the guards
below, and the cluster has room (read-only kubeconfig). The stored template
has no Git link, so saving it commits nothing anywhere. Undo is
otii/northflank/remove.py.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
sys.path.insert(0, str(HERE))
from nf import call, die, token, unwrap  # noqa: E402

POLL_SECONDS = 30
RUN_TIMEOUT_SECONDS = 60 * 60
PLAN_CAPS_MI = {"learn-api": 768, "learn-web": 512, "learn-job": 384, "learn-build": 4096}
NAME_PREFIXES = ("learn-", "otii-learn")
STORAGE_WORKLOADS = ("learn-api", "learn-setup")
# Generated once by Northflank and kept across releases. A randomSecret in a
# template ARGUMENT is drawn again on every run (it rotated the Keycloak
# client secret and the webhook secret under otii on staging, 30 Sep 2026);
# one in the stored template's argument overrides is drawn once and kept.
SECRET_ARGS = ("dbPassword", "jwtSecret", "collabKey", "adminPassword", "kcClientSecret", "webhookSecret")
DESCRIPTION_OK = re.compile(r"^[a-zA-Z0-9.,?\s\\/'\"()\[\];`%^&*\-_:!]+$")


def sh(*args: str) -> str:
    return subprocess.run(args, cwd=ROOT, check=True, capture_output=True, text=True).stdout.strip()


def nodes(tree):
    """Template nodes, not the resource kinds a Condition waits on."""
    if isinstance(tree, dict):
        if "kind" in tree:
            yield tree
            if tree["kind"] == "Condition":
                return
        for value in tree.values():
            yield from nodes(value)
    elif isinstance(tree, list):
        for value in tree:
            yield from nodes(value)


def guard(template: dict, arguments: dict | None = None) -> None:
    """Every rule here is one Otii Learn must never break on a shared otii project."""
    problems = []
    if "gitops" in template:
        problems.append("template has a Git link")
    for node in nodes(template["spec"]):
        kind, spec = node["kind"], node.get("spec", {})
        if kind in ("Project", "Addon", "BYOCCluster"):
            problems.append(f"declares a {kind}: Otii Learn owns no project, database server or Redis")
        name = spec.get("name") if isinstance(spec, dict) else None
        if name and kind not in ("Condition",) and not name.startswith(NAME_PREFIXES):
            problems.append(f"{kind} {name} is not named learn-* or otii-learn*")
        description = spec.get("description", "") if isinstance(spec, dict) else ""
        if description and (len(description) > 200 or not DESCRIPTION_OK.match(description)):
            problems.append(f"{kind} {name}: description too long or has characters Northflank refuses")
        if kind == "CustomPlan":
            mem = spec["configuration"]["resources"]["memory"]["resources"]["limit"]
            if mem > PLAN_CAPS_MI.get(name, 0):
                problems.append(f"plan {name} asks {mem} MiB, cap is {PLAN_CAPS_MI.get(name)}")
    args = template["arguments"]
    for key in ("dbPassword", "jwtSecret", "collabKey", "adminPassword", "kcClientSecret", "webhookSecret"):
        if not str(args.get(key, "")).startswith("${fn.randomSecret("):
            problems.append(f"argument {key} must be generated by Northflank, not written in the file")
    for key in ("dbHost", "redisHost"):
        if re.search(r"\.(code\.run|northflank\.com)$", args.get(key, "")):
            problems.append(f"{key} uses Northflank's addon DNS; use the in-cluster service name")
    # otii's environment label hands a workload every otii setting of that
    # environment. Only the two that store files need it; learn-web would
    # also pick up otii's Stripe names, which LearnHouse's web app reads.
    for node in nodes(template["spec"]):
        spec = node.get("spec", {})
        if isinstance(spec, dict) and "${args.otiiEnvTag}" in (spec.get("tags") or []):
            if node["kind"] != "SecretGroup" and spec.get("name") not in STORAGE_WORKLOADS:
                problems.append(f"{spec.get('name')} carries otii's environment label; only {STORAGE_WORKLOADS} may")
    run = {**args, **(arguments or {})}
    if run.get("s3KeyPrefix") != f"{run.get('otiiEnvTag')}/otii-learn/":
        problems.append("s3KeyPrefix must be <otii environment>/otii-learn/, e.g. staging/otii-learn/")
    if problems:
        die("guards failed:\n  " + "\n  ".join(problems))
    print("ok  guards pass")


def check_room() -> None:
    """Read-only: every node's allocatable memory minus what pods already request."""
    kubeconfig = Path("~/.kube/config-civo").expanduser()
    out = subprocess.run(["kubectl", "--kubeconfig", str(kubeconfig), "get", "nodes,pods", "-A", "-o", "json"],
                         capture_output=True, text=True)
    if out.returncode != 0:
        die("could not read the cluster to check room")
    items = json.loads(out.stdout)["items"]

    def mi(q: str) -> float:
        units = {"Ki": 1 / 1024, "Mi": 1, "Gi": 1024, "k": 1e3 / 1048576, "M": 1e6 / 1048576, "G": 1e9 / 1048576}
        for unit in sorted(units, key=len, reverse=True):
            if q.endswith(unit):
                return float(q[: -len(unit)]) * units[unit]
        return float(q) / 1048576

    free = {}
    for node in (i for i in items if i["kind"] == "Node"):
        free[node["metadata"]["name"]] = mi(node["status"]["allocatable"]["memory"])
    for pod in (i for i in items if i["kind"] == "Pod" and i["status"].get("phase") in ("Running", "Pending")):
        host = pod["spec"].get("nodeName")
        if host in free:
            for container in pod["spec"]["containers"]:
                free[host] -= mi(container.get("resources", {}).get("requests", {}).get("memory", "0"))
    need = [384 + 64, 256 + 64, 2048]  # api, web (with sidecars), one build at a time
    largest = max(free.values())
    total = sum(free.values())
    print(f"    room: {total:.0f} MiB free across nodes, largest single space {largest:.0f} MiB")
    if largest < max(need) or total < sum(need) + 1024:
        die("not enough room in the cluster for Otii Learn and one build")
    print("ok  room for Otii Learn and one build")


def carry_linked_routes(tok: str, template: dict, project: str, domain: str) -> None:
    """Routes already linked to the live learn services stay linked.

    The file declares none: from scratch there are none yet (subdomain.py
    routes runs after the first release). Northflank refuses a run whose
    port list would unlink a route that exists (staging, 30 Sep 2026), so
    each run carries over what is linked, and only under this environment's
    address."""
    for node in nodes(template["spec"]):
        if node["kind"] != "DeploymentService":
            continue
        name = node["spec"]["name"]
        code, body = call(tok, "GET", f"/projects/{project}/services/{name}")
        if code == 404:
            continue
        if code >= 300:
            die(f"reading service {name} failed with HTTP {code}: {json.dumps(body)[:400]}")
        live = {p.get("name"): p.get("domains") or [] for p in unwrap(body).get("ports", [])}
        for port in node["spec"].get("ports", []):
            port["domains"] = [d for d in live.get(port["name"], [])
                               if d == domain or d.startswith(domain + "/")]
            for route in port["domains"]:
                print(f"    keeps route {route} -> {name}:{port['name']}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("env", choices=["staging", "production"])
    parser.add_argument("--confirm-production", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.env == "production" and not args.confirm_production:
        die("production needs --confirm-production, given only on an explicit go-ahead")

    template = json.loads((HERE / "template.json").read_text())
    arguments = json.loads((HERE / f"{args.env}-arguments.json").read_text())
    guard(template, arguments)
    check_room()

    if sh("git", "status", "--porcelain"):
        die("the working tree has uncommitted changes")
    sh("git", "fetch", "-q", "origin", template["arguments"]["gitBranch"])
    sha = sh("git", "rev-parse", "HEAD")
    if sha != sh("git", "rev-parse", f"origin/{template['arguments']['gitBranch']}"):
        die("HEAD is not what origin has; push first")
    # Images depend only on apps/api and apps/web: build the last commit that
    # changed them, so template or script changes reuse the images already built.
    image_sha = sh("git", "log", "-1", "--format=%H", "--", "apps/api", "apps/web")
    print(f"ok  releasing commit {sha[:12]} (images from {image_sha[:12]})")
    if args.check:
        return 0

    tok = token()
    carry_linked_routes(tok, template, arguments["projectName"], arguments["domain"])
    want = dict(template, name=f"otii-learn-{args.env}")
    name = want["name"]
    code, body = call(tok, "GET", f"/templates/{name}")
    stored = unwrap(body) if code < 300 else {}
    overrides = dict(stored.get("argumentOverrides") or {})
    fresh = [k for k in SECRET_ARGS if k not in overrides]
    for key in fresh:
        overrides[key] = template["arguments"][key]  # the ${fn.randomSecret(n)} expression, drawn once
    want["argumentOverrides"] = overrides
    if code == 404:
        code, body = call(tok, "POST", "/templates", want)
    elif code < 300:
        if "gitops" in stored:
            die(f"stored template {name} has a Git link; refusing")
        code, body = call(tok, "POST", f"/templates/{name}", want)
    if code >= 300:
        die(f"saving template {name} failed with HTTP {code}: {json.dumps(body)[:800]}")
    code, body = call(tok, "GET", f"/templates/{name}")
    live = unwrap(body)
    if code >= 300 or "gitops" in live or live.get("spec") != want["spec"]:
        die(f"template {name} does not read back equal to the file")
    missing = [k for k in SECRET_ARGS if k not in (live.get("argumentOverrides") or {})]
    if missing:
        die(f"template {name} does not keep these secrets across runs: {missing}")
    print(f"ok  template {name} saved and reads back equal, no Git link")
    if fresh:
        print(f"    secrets drawn on this run and kept from now on: {', '.join(fresh)}")
        print("    otii's side reads two of them (Keycloak client secret, webhook secret): run kc-bootstrap"
              " and release or restart otii's backend after this run")

    run_args = {k: v for k, v in arguments.items() if k in template["arguments"]}
    run_args["releaseSha"] = image_sha
    code, body = call(tok, "POST", f"/templates/{name}/runs", {"arguments": run_args})
    if code >= 300:
        die(f"starting the run failed with HTTP {code}: {json.dumps(body)[:800]}")
    run_id = unwrap(body).get("id")
    print(f"ok  run {run_id} started")
    deadline, last = time.time() + RUN_TIMEOUT_SECONDS, None
    while time.time() < deadline:
        code, body = call(tok, "GET", f"/templates/{name}/runs/{run_id}")
        run = unwrap(body) if code < 300 else {}
        status = run.get("status")
        if status != last:
            print(f"    run {run_id}: {status}")
            last = status
        if run.get("concluded") or status in ("success", "failure", "aborted"):
            errors = []
            for node in nodes(run.get("spec", {})):
                resp = node.get("response")
                if isinstance(resp, dict) and isinstance(resp.get("error"), dict):
                    errors.append(f"{node.get('ref') or node['kind']}: {str(resp['error'].get('message'))[:300]}")
            for line in errors:
                print(f"    {line}")
            return 0 if status == "success" and not errors else 1
        time.sleep(POLL_SECONDS)
    die(f"run {run_id} did not finish in {RUN_TIMEOUT_SECONDS // 60} minutes")
    return 1


if __name__ == "__main__":
    sys.exit(main())
